build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs "
  contactDetails:
    name: "Jim Smith - QA Lead"
    email: "jim@eazybank.com"
  onCallSupport:
    - (555) 555-2345
    - (555) 523-6789