build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank cards related QA APIs "
  contactDetails:
    name: "James Smythe - QA Lead"
    email: "james.s@eazybank.com"
  onCallSupport:
    - (555) 592-421
    - (555) 523-6889