build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related prod APIs "
  contactDetails:
    name: "Simon Morgan - Product Owner"
    email: "simonmorgan@eazybank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384